### PR TITLE
Allow to load pdf document from Stream or byte array

### PR DESCRIPTION
**Pull request by quangtrinh-spce**

### CODE REVIEW

**Comment by chrisjust** [comment]
@quangtrinh-spce any chance of this coming out? :-)

**Comment by DJGosnell** [comment]
This will work, but my concern is the performance.  When using a memory stream of no specified size, the buffer will re-create a byte array and copy the data multiple times until the byte array is sufficient size enough.

The process looks like the following with this PR.

1. Memory stream is used to create a byte array multiple times until it is of sufficient size.
2. The memory stream byte array is copied to a new array and then passed to the `Load` method.
3. Load method allocates the bull byte array size and marshals it.
4. Byte array passed to `Load` is then copies into the new byte array.

The issue is this may not be a problem for one-off loads, but when this package is used in a server situation, initializing and copying the byte array at a minimum of 3 times is excessive, especially when a PDF document can sometimes be very large.

This is one of the preferred methods of loading a PDF document from a stream.  The memory stream size is set (if available) and then the byte array is only initialized once.
See https://github.com/Dtronix/PDFiumCore/issues/8

I've just not gotten around to implementing this yet...
```csharp
public unsafe void FPDF_LoadMemDocument() 
 { 
     using var fs = File.OpenRead("pdf-sample.pdf"); 
     var fileBytes = new byte[fs.Length]; 
     using var ms = new MemoryStream(fileBytes); 
  
     // Copy file the underlying byte stream. 
     fs.CopyTo(ms); 
  
     fixed (void* ptr = fileBytes) 
     { 
         var document = fpdfview.FPDF_LoadMemDocument(new IntPtr(ptr), fileBytes.Length, null); 
         Assert.AreEqual(1, fpdfview.FPDF_GetPageCount(document)); 
     } 
 } 
```

**Comment by quangtrinh-spce** [comment]
Hmm, your concern was right. I will check the performance issue and make an update soon.

**Comment by DJGosnell** [comment]
Added into the latest version.
https://github.com/Dtronix/DtronixPdf/blob/dfba6ffadb06dcb7e647c670e6ed3c46e8a215ef/src/DtronixPdf/PdfDocument.cs#L45

Usage can be seen below.

https://github.com/Dtronix/DtronixPdf/blob/dfba6ffadb06dcb7e647c670e6ed3c46e8a215ef/src/DtronixPdf.Tests/PdfDocumentTests.cs#L17-L22

**Pull request closed without merging**
